// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb.Enum {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgdwYl9lbnVtKrwBCglFcnJvckNvZGUSCwoHRGVmYXVs",
            "dBAAEgYKAk9LEAESDgoKRW50cnlFcnJvchACEh8KG0xvZ2luQWNjb3VudE9y",
            "UGFzc3dvcmRFcnJvchADEhcKE1JlZ2lzdGVyQWNjb3VudEV4aXQQBBIOCgpB",
            "dXRoRmFpbGVkEAUSEgoOUm9vbVVuRXhpc3RlbnQQBhIVChFSb29tUGFzc3dv",
            "cmRFcnJvchAHEhUKEVVzZXJBbHJlYWR5SW5Sb29tEAgqJwoDU2V4EgoKBlVu",
            "a25vdxAAEggKBE1hbGUQARIKCgZGZW1hbGUQAkIdWhFzZXJ2ZXIvcGIvcGJf",
            "ZW51baoCB1BiLkVudW1iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.Enum.ErrorCode), typeof(global::Pb.Enum.Sex), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    /// <summary>
    ///默认值0
    /// </summary>
    [pbr::OriginalName("Default")] Default = 0,
    /// <summary>
    ///成功
    /// </summary>
    [pbr::OriginalName("OK")] Ok = 1,
    /// <summary>
    ///检验到客户端连接验证码失败（Entry模块握手失败）
    /// </summary>
    [pbr::OriginalName("EntryError")] EntryError = 2,
    /// <summary>
    ///登录账号或密码错误（登录）
    /// </summary>
    [pbr::OriginalName("LoginAccountOrPasswordError")] LoginAccountOrPasswordError = 3,
    /// <summary>
    ///账号已存在（注册）
    /// </summary>
    [pbr::OriginalName("RegisterAccountExit")] RegisterAccountExit = 4,
    /// <summary>
    ///授权失败（先登录再进行长连接）
    /// </summary>
    [pbr::OriginalName("AuthFailed")] AuthFailed = 5,
    /// <summary>
    ///房间不存在
    /// </summary>
    [pbr::OriginalName("RoomUnExistent")] RoomUnExistent = 6,
    /// <summary>
    ///房间密码错误
    /// </summary>
    [pbr::OriginalName("RoomPasswordError")] RoomPasswordError = 7,
    /// <summary>
    ///玩家已在房间中，不能再创建房间
    /// </summary>
    [pbr::OriginalName("UserAlreadyInRoom")] UserAlreadyInRoom = 8,
  }

  public enum Sex {
    /// <summary>
    ///春哥
    /// </summary>
    [pbr::OriginalName("Unknow")] Unknow = 0,
    /// <summary>
    ///男
    /// </summary>
    [pbr::OriginalName("Male")] Male = 1,
    /// <summary>
    ///女
    /// </summary>
    [pbr::OriginalName("Female")] Female = 2,
  }

  #endregion

}

#endregion Designer generated code
