// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Pb.Enum {

  /// <summary>Holder for reflection information generated from enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgplbnVtLnByb3RvEgdwYl9lbnVtKskBCglFcnJvckNvZGUSCwoHRGVmYXVs",
            "dBAAEgYKAk9LEAESDgoKRW50cnlFcnJvchACEhoKFkxvZ2luQWNjb3VudFVu",
            "RXhpeHRlbnQQAxIWChJMb2dpblBhc3N3b3JkRXJyb3IQBBIXChNSZWdpc3Rl",
            "ckFjY291bnRFeGl0EAUSDgoKQXV0aEZhaWxlZBAGEhIKDlJvb21VbkV4aXN0",
            "ZW50EAcSEgoORGVza1VuRXhpc3RlbnQQCBISCg5EZXNrUGxheWVyRnVsbBAJ",
            "KicKA1NleBIKCgZVbmtub3cQABIICgRNYWxlEAESCgoGRmVtYWxlEAJCHVoR",
            "c2VydmVyL3BiL3BiX2VudW2qAgdQYi5FbnVtYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Pb.Enum.ErrorCode), typeof(global::Pb.Enum.Sex), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    /// <summary>
    ///默认值0
    /// </summary>
    [pbr::OriginalName("Default")] Default = 0,
    /// <summary>
    ///成功
    /// </summary>
    [pbr::OriginalName("OK")] Ok = 1,
    /// <summary>
    ///检验到客户端连接验证码失败（Entry模块握手失败）
    /// </summary>
    [pbr::OriginalName("EntryError")] EntryError = 2,
    /// <summary>
    ///登录账号不存在
    /// </summary>
    [pbr::OriginalName("LoginAccountUnExixtent")] LoginAccountUnExixtent = 3,
    /// <summary>
    ///登录密码错误
    /// </summary>
    [pbr::OriginalName("LoginPasswordError")] LoginPasswordError = 4,
    /// <summary>
    ///注册账号已存在
    /// </summary>
    [pbr::OriginalName("RegisterAccountExit")] RegisterAccountExit = 5,
    /// <summary>
    ///授权失败（先登录再进行长连接）
    /// </summary>
    [pbr::OriginalName("AuthFailed")] AuthFailed = 6,
    /// <summary>
    ///房间不存在
    /// </summary>
    [pbr::OriginalName("RoomUnExistent")] RoomUnExistent = 7,
    /// <summary>
    ///桌子不存在
    /// </summary>
    [pbr::OriginalName("DeskUnExistent")] DeskUnExistent = 8,
    /// <summary>
    ///桌子上玩家已满
    /// </summary>
    [pbr::OriginalName("DeskPlayerFull")] DeskPlayerFull = 9,
  }

  public enum Sex {
    /// <summary>
    ///春哥
    /// </summary>
    [pbr::OriginalName("Unknow")] Unknow = 0,
    /// <summary>
    ///男
    /// </summary>
    [pbr::OriginalName("Male")] Male = 1,
    /// <summary>
    ///女
    /// </summary>
    [pbr::OriginalName("Female")] Female = 2,
  }

  #endregion

}

#endregion Designer generated code
