// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: error_code.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace PbCommon {

  /// <summary>Holder for reflection information generated from error_code.proto</summary>
  public static partial class ErrorCodeReflection {

    #region Descriptor
    /// <summary>File descriptor for error_code.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ErrorCodeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBlcnJvcl9jb2RlLnByb3RvEglwYl9jb21tb24qvAEKCUVycm9yQ29kZRIL",
            "CgdEZWZhdWx0EAASBgoCT0sQARIOCgpFbnRyeUVycm9yEAISHwobTG9naW5B",
            "Y2NvdW50T3JQYXNzd29yZEVycm9yEAMSFwoTUmVnaXN0ZXJBY2NvdW50RXhp",
            "dBAEEg4KCkF1dGhGYWlsZWQQBRISCg5Sb29tVW5FeGlzdGVudBAGEhUKEVJv",
            "b21QYXNzd29yZEVycm9yEAcSFQoRVXNlckFscmVhZHlJblJvb20QCEIVWhNz",
            "ZXJ2ZXIvcGIvcGJfY29tbW9uYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PbCommon.ErrorCode), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum ErrorCode {
    /// <summary>
    ///默认值0
    /// </summary>
    [pbr::OriginalName("Default")] Default = 0,
    /// <summary>
    ///成功
    /// </summary>
    [pbr::OriginalName("OK")] Ok = 1,
    /// <summary>
    ///检验到客户端连接验证码失败（Entry模块握手失败）
    /// </summary>
    [pbr::OriginalName("EntryError")] EntryError = 2,
    /// <summary>
    ///登录账号或密码错误（登录）
    /// </summary>
    [pbr::OriginalName("LoginAccountOrPasswordError")] LoginAccountOrPasswordError = 3,
    /// <summary>
    ///账号已存在（注册）
    /// </summary>
    [pbr::OriginalName("RegisterAccountExit")] RegisterAccountExit = 4,
    /// <summary>
    ///授权失败（先登录再进行长连接）
    /// </summary>
    [pbr::OriginalName("AuthFailed")] AuthFailed = 5,
    /// <summary>
    ///房间不存在
    /// </summary>
    [pbr::OriginalName("RoomUnExistent")] RoomUnExistent = 6,
    /// <summary>
    ///房间密码错误
    /// </summary>
    [pbr::OriginalName("RoomPasswordError")] RoomPasswordError = 7,
    /// <summary>
    ///玩家已在房间中，不能再创建房间
    /// </summary>
    [pbr::OriginalName("UserAlreadyInRoom")] UserAlreadyInRoom = 8,
  }

  #endregion

}

#endregion Designer generated code
