// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: error_code.proto

package pb_common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_Default                     ErrorCode = 0 //默认值0
	ErrorCode_OK                          ErrorCode = 1 //成功
	ErrorCode_EntryError                  ErrorCode = 2 //检验到客户端连接验证码失败（Entry模块握手失败）
	ErrorCode_LoginAccountOrPasswordError ErrorCode = 3 //登录账号或密码错误（登录）
	ErrorCode_RegisterAccountExit         ErrorCode = 4 //账号已存在（注册）
	ErrorCode_AuthFailed                  ErrorCode = 5 //授权失败（先登录再进行长连接）
	ErrorCode_RoomUnExistent              ErrorCode = 6 //房间不存在
	ErrorCode_RoomPasswordError           ErrorCode = 7 //房间密码错误
	ErrorCode_UserAlreadyInRoom           ErrorCode = 8 //玩家已在房间中，不能再创建房间
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "Default",
		1: "OK",
		2: "EntryError",
		3: "LoginAccountOrPasswordError",
		4: "RegisterAccountExit",
		5: "AuthFailed",
		6: "RoomUnExistent",
		7: "RoomPasswordError",
		8: "UserAlreadyInRoom",
	}
	ErrorCode_value = map[string]int32{
		"Default":                     0,
		"OK":                          1,
		"EntryError":                  2,
		"LoginAccountOrPasswordError": 3,
		"RegisterAccountExit":         4,
		"AuthFailed":                  5,
		"RoomUnExistent":              6,
		"RoomPasswordError":           7,
		"UserAlreadyInRoom":           8,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_error_code_proto_rawDescGZIP(), []int{0}
}

var File_error_code_proto protoreflect.FileDescriptor

var file_error_code_proto_rawDesc = []byte{
	0x0a, 0x10, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0xbc, 0x01,
	0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x02,
	0x12, 0x1f, 0x0a, 0x1b, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x4f, 0x72, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10,
	0x03, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x45, 0x78, 0x69, 0x74, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x75,
	0x74, 0x68, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x6f,
	0x6f, 0x6d, 0x55, 0x6e, 0x45, 0x78, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x10, 0x06, 0x12, 0x15,
	0x0a, 0x11, 0x52, 0x6f, 0x6f, 0x6d, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x10, 0x07, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x73, 0x65, 0x72, 0x41, 0x6c, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x49, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x08, 0x42, 0x15, 0x5a, 0x13,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x62, 0x5f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_error_code_proto_rawDescOnce sync.Once
	file_error_code_proto_rawDescData = file_error_code_proto_rawDesc
)

func file_error_code_proto_rawDescGZIP() []byte {
	file_error_code_proto_rawDescOnce.Do(func() {
		file_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_error_code_proto_rawDescData)
	})
	return file_error_code_proto_rawDescData
}

var file_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_error_code_proto_goTypes = []interface{}{
	(ErrorCode)(0), // 0: pb_common.ErrorCode
}
var file_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_error_code_proto_init() }
func file_error_code_proto_init() {
	if File_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_error_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_error_code_proto_goTypes,
		DependencyIndexes: file_error_code_proto_depIdxs,
		EnumInfos:         file_error_code_proto_enumTypes,
	}.Build()
	File_error_code_proto = out.File
	file_error_code_proto_rawDesc = nil
	file_error_code_proto_goTypes = nil
	file_error_code_proto_depIdxs = nil
}
