// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: bjl.proto

package pb_bjl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BjlLevel int32

const (
	BjlLevel_Primary BjlLevel = 0 //初级场
	BjlLevel_Middle  BjlLevel = 1 //中级场
	BjlLevel_High    BjlLevel = 2 //高级场
	BjlLevel_King    BjlLevel = 3 //至尊场
)

// Enum value maps for BjlLevel.
var (
	BjlLevel_name = map[int32]string{
		0: "Primary",
		1: "Middle",
		2: "High",
		3: "King",
	}
	BjlLevel_value = map[string]int32{
		"Primary": 0,
		"Middle":  1,
		"High":    2,
		"King":    3,
	}
)

func (x BjlLevel) Enum() *BjlLevel {
	p := new(BjlLevel)
	*p = x
	return p
}

func (x BjlLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BjlLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[0].Descriptor()
}

func (BjlLevel) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[0]
}

func (x BjlLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BjlLevel.Descriptor instead.
func (BjlLevel) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{0}
}

//下注区域
type EnumBetArea int32

const (
	EnumBetArea_AreaXian      EnumBetArea = 0
	EnumBetArea_AreaZhuang    EnumBetArea = 1
	EnumBetArea_AreaHe        EnumBetArea = 2
	EnumBetArea_AreaXianDui   EnumBetArea = 3
	EnumBetArea_AreaZhuangDui EnumBetArea = 4
)

// Enum value maps for EnumBetArea.
var (
	EnumBetArea_name = map[int32]string{
		0: "AreaXian",
		1: "AreaZhuang",
		2: "AreaHe",
		3: "AreaXianDui",
		4: "AreaZhuangDui",
	}
	EnumBetArea_value = map[string]int32{
		"AreaXian":      0,
		"AreaZhuang":    1,
		"AreaHe":        2,
		"AreaXianDui":   3,
		"AreaZhuangDui": 4,
	}
)

func (x EnumBetArea) Enum() *EnumBetArea {
	p := new(EnumBetArea)
	*p = x
	return p
}

func (x EnumBetArea) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumBetArea) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[1].Descriptor()
}

func (EnumBetArea) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[1]
}

func (x EnumBetArea) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumBetArea.Descriptor instead.
func (EnumBetArea) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{1}
}

type EnumWinType int32

const (
	EnumWinType_Xian   EnumWinType = 0 //闲赢
	EnumWinType_Zhuang EnumWinType = 1 //庄赢
	EnumWinType_He     EnumWinType = 2 //和
)

// Enum value maps for EnumWinType.
var (
	EnumWinType_name = map[int32]string{
		0: "Xian",
		1: "Zhuang",
		2: "He",
	}
	EnumWinType_value = map[string]int32{
		"Xian":   0,
		"Zhuang": 1,
		"He":     2,
	}
)

func (x EnumWinType) Enum() *EnumWinType {
	p := new(EnumWinType)
	*p = x
	return p
}

func (x EnumWinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnumWinType) Descriptor() protoreflect.EnumDescriptor {
	return file_bjl_proto_enumTypes[2].Descriptor()
}

func (EnumWinType) Type() protoreflect.EnumType {
	return &file_bjl_proto_enumTypes[2]
}

func (x EnumWinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnumWinType.Descriptor instead.
func (EnumWinType) EnumDescriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{2}
}

type ReqJoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReqJoinRoom) Reset() {
	*x = ReqJoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinRoom) ProtoMessage() {}

func (x *ReqJoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinRoom.ProtoReflect.Descriptor instead.
func (*ReqJoinRoom) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{0}
}

type RespJoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info []*RespJoinRoom_DeskInfo `protobuf:"bytes,1,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *RespJoinRoom) Reset() {
	*x = RespJoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinRoom) ProtoMessage() {}

func (x *RespJoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinRoom.ProtoReflect.Descriptor instead.
func (*RespJoinRoom) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{1}
}

func (x *RespJoinRoom) GetInfo() []*RespJoinRoom_DeskInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type ReqJoinDesk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeskId string `protobuf:"bytes,1,opt,name=DeskId,proto3" json:"DeskId,omitempty"`
}

func (x *ReqJoinDesk) Reset() {
	*x = ReqJoinDesk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqJoinDesk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqJoinDesk) ProtoMessage() {}

func (x *ReqJoinDesk) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqJoinDesk.ProtoReflect.Descriptor instead.
func (*ReqJoinDesk) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{2}
}

func (x *ReqJoinDesk) GetDeskId() string {
	if x != nil {
		return x.DeskId
	}
	return ""
}

type RespJoinDesk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus string     `protobuf:"bytes,1,opt,name=GameStatus,proto3" json:"GameStatus,omitempty"` //当前房间的状态
	BetInfos   []*BetInfo `protobuf:"bytes,2,rep,name=BetInfos,proto3" json:"BetInfos,omitempty"`     //桌子上下注信息
}

func (x *RespJoinDesk) Reset() {
	*x = RespJoinDesk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinDesk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinDesk) ProtoMessage() {}

func (x *RespJoinDesk) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinDesk.ProtoReflect.Descriptor instead.
func (*RespJoinDesk) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{3}
}

func (x *RespJoinDesk) GetGameStatus() string {
	if x != nil {
		return x.GameStatus
	}
	return ""
}

func (x *RespJoinDesk) GetBetInfos() []*BetInfo {
	if x != nil {
		return x.BetInfos
	}
	return nil
}

type BetInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID   int64       `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"`                           //下注的人
	Area  EnumBetArea `protobuf:"varint,2,opt,name=Area,proto3,enum=pb_bjl.EnumBetArea" json:"Area,omitempty"` //下注区域
	Count uint32      `protobuf:"varint,3,opt,name=Count,proto3" json:"Count,omitempty"`                       //区域内下注总额
}

func (x *BetInfo) Reset() {
	*x = BetInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BetInfo) ProtoMessage() {}

func (x *BetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BetInfo.ProtoReflect.Descriptor instead.
func (*BetInfo) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{4}
}

func (x *BetInfo) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

func (x *BetInfo) GetArea() EnumBetArea {
	if x != nil {
		return x.Area
	}
	return EnumBetArea_AreaXian
}

func (x *BetInfo) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//状态机变化
type BroadcastStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameStatus string `protobuf:"bytes,1,opt,name=GameStatus,proto3" json:"GameStatus,omitempty"` //状态变化
}

func (x *BroadcastStatusChange) Reset() {
	*x = BroadcastStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastStatusChange) ProtoMessage() {}

func (x *BroadcastStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastStatusChange.ProtoReflect.Descriptor instead.
func (*BroadcastStatusChange) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{5}
}

func (x *BroadcastStatusChange) GetGameStatus() string {
	if x != nil {
		return x.GameStatus
	}
	return ""
}

//同步玩家下注
type BroadcastPlayerBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *BetInfo `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"` //下注信息
}

func (x *BroadcastPlayerBet) Reset() {
	*x = BroadcastPlayerBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastPlayerBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastPlayerBet) ProtoMessage() {}

func (x *BroadcastPlayerBet) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastPlayerBet.ProtoReflect.Descriptor instead.
func (*BroadcastPlayerBet) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{6}
}

func (x *BroadcastPlayerBet) GetInfo() *BetInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

//玩家自己下注
type NotifyBet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area  EnumBetArea `protobuf:"varint,1,opt,name=Area,proto3,enum=pb_bjl.EnumBetArea" json:"Area,omitempty"` //下注区域
	Count uint32      `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`                       //区域内下注总额
}

func (x *NotifyBet) Reset() {
	*x = NotifyBet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NotifyBet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyBet) ProtoMessage() {}

func (x *NotifyBet) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyBet.ProtoReflect.Descriptor instead.
func (*NotifyBet) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyBet) GetArea() EnumBetArea {
	if x != nil {
		return x.Area
	}
	return EnumBetArea_AreaXian
}

func (x *NotifyBet) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

//广播桌子上牌
type BroadcastPokerShow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Xian   []int32 `protobuf:"varint,1,rep,packed,name=Xian,proto3" json:"Xian,omitempty"`     //闲区域的扑克牌id
	Zhuang []int32 `protobuf:"varint,2,rep,packed,name=Zhuang,proto3" json:"Zhuang,omitempty"` //庄区域的扑克牌id
}

func (x *BroadcastPokerShow) Reset() {
	*x = BroadcastPokerShow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BroadcastPokerShow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastPokerShow) ProtoMessage() {}

func (x *BroadcastPokerShow) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastPokerShow.ProtoReflect.Descriptor instead.
func (*BroadcastPokerShow) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{8}
}

func (x *BroadcastPokerShow) GetXian() []int32 {
	if x != nil {
		return x.Xian
	}
	return nil
}

func (x *BroadcastPokerShow) GetZhuang() []int32 {
	if x != nil {
		return x.Zhuang
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WinType     EnumWinType `protobuf:"varint,1,opt,name=WinType,proto3,enum=pb_bjl.EnumWinType" json:"WinType,omitempty"`
	IsXianDui   bool        `protobuf:"varint,2,opt,name=IsXianDui,proto3" json:"IsXianDui,omitempty"`
	IsZhuangDui bool        `protobuf:"varint,3,opt,name=IsZhuangDui,proto3" json:"IsZhuangDui,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{9}
}

func (x *Result) GetWinType() EnumWinType {
	if x != nil {
		return x.WinType
	}
	return EnumWinType_Xian
}

func (x *Result) GetIsXianDui() bool {
	if x != nil {
		return x.IsXianDui
	}
	return false
}

func (x *Result) GetIsZhuangDui() bool {
	if x != nil {
		return x.IsZhuangDui
	}
	return false
}

type RespJoinRoom_DeskInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level       BjlLevel `protobuf:"varint,1,opt,name=Level,proto3,enum=pb_bjl.BjlLevel" json:"Level,omitempty"`
	DeskId      string   `protobuf:"bytes,2,opt,name=DeskId,proto3" json:"DeskId,omitempty"`
	PlayerCount uint32   `protobuf:"varint,3,opt,name=PlayerCount,proto3" json:"PlayerCount,omitempty"`
}

func (x *RespJoinRoom_DeskInfo) Reset() {
	*x = RespJoinRoom_DeskInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bjl_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RespJoinRoom_DeskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespJoinRoom_DeskInfo) ProtoMessage() {}

func (x *RespJoinRoom_DeskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bjl_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespJoinRoom_DeskInfo.ProtoReflect.Descriptor instead.
func (*RespJoinRoom_DeskInfo) Descriptor() ([]byte, []int) {
	return file_bjl_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RespJoinRoom_DeskInfo) GetLevel() BjlLevel {
	if x != nil {
		return x.Level
	}
	return BjlLevel_Primary
}

func (x *RespJoinRoom_DeskInfo) GetDeskId() string {
	if x != nil {
		return x.DeskId
	}
	return ""
}

func (x *RespJoinRoom_DeskInfo) GetPlayerCount() uint32 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

var File_bjl_proto protoreflect.FileDescriptor

var file_bjl_proto_rawDesc = []byte{
	0x0a, 0x09, 0x62, 0x6a, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f,
	0x62, 0x6a, 0x6c, 0x22, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x22, 0xaf, 0x01, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x52,
	0x6f, 0x6f, 0x6d, 0x12, 0x31, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x6c, 0x0a, 0x08, 0x44, 0x65, 0x73, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x26, 0x0a, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x42, 0x6a, 0x6c, 0x4c, 0x65,
	0x76, 0x65, 0x6c, 0x52, 0x05, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65,
	0x73, 0x6b, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x73, 0x6b,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x4a, 0x6f, 0x69, 0x6e, 0x44,
	0x65, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x65, 0x73, 0x6b, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x65, 0x73, 0x6b, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x0c, 0x52,
	0x65, 0x73, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x65, 0x73, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x08, 0x42,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08,
	0x42, 0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x5a, 0x0a, 0x07, 0x42, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x55, 0x49, 0x44, 0x12, 0x27, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x42, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x15, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x39, 0x0a,
	0x12, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x42, 0x65, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x42, 0x65, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x4a, 0x0a, 0x09, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x79, 0x42, 0x65, 0x74, 0x12, 0x27, 0x0a, 0x04, 0x41, 0x72, 0x65, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75,
	0x6d, 0x42, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x52, 0x04, 0x41, 0x72, 0x65, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x40, 0x0a, 0x12, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73,
	0x74, 0x50, 0x6f, 0x6b, 0x65, 0x72, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04, 0x58, 0x69,
	0x61, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x04, 0x58, 0x69, 0x61, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52, 0x06,
	0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x22, 0x77, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x2d, 0x0a, 0x07, 0x57, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x13, 0x2e, 0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0x2e, 0x45, 0x6e, 0x75, 0x6d, 0x57,
	0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x57, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x49, 0x73, 0x58, 0x69, 0x61, 0x6e, 0x44, 0x75, 0x69, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x49, 0x73, 0x58, 0x69, 0x61, 0x6e, 0x44, 0x75, 0x69, 0x12, 0x20, 0x0a,
	0x0b, 0x49, 0x73, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x44, 0x75, 0x69, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x49, 0x73, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x44, 0x75, 0x69, 0x2a,
	0x37, 0x0a, 0x08, 0x42, 0x6a, 0x6c, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x0b, 0x0a, 0x07, 0x50,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x69, 0x64, 0x64,
	0x6c, 0x65, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x69, 0x67, 0x68, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x67, 0x10, 0x03, 0x2a, 0x5b, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d,
	0x42, 0x65, 0x74, 0x41, 0x72, 0x65, 0x61, 0x12, 0x0c, 0x0a, 0x08, 0x41, 0x72, 0x65, 0x61, 0x58,
	0x69, 0x61, 0x6e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x72, 0x65, 0x61, 0x5a, 0x68, 0x75,
	0x61, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x72, 0x65, 0x61, 0x48, 0x65, 0x10,
	0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x72, 0x65, 0x61, 0x58, 0x69, 0x61, 0x6e, 0x44, 0x75, 0x69,
	0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x72, 0x65, 0x61, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67,
	0x44, 0x75, 0x69, 0x10, 0x04, 0x2a, 0x2b, 0x0a, 0x0b, 0x45, 0x6e, 0x75, 0x6d, 0x57, 0x69, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x58, 0x69, 0x61, 0x6e, 0x10, 0x00, 0x12, 0x0a,
	0x0a, 0x06, 0x5a, 0x68, 0x75, 0x61, 0x6e, 0x67, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x65,
	0x10, 0x02, 0x42, 0x1b, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f,
	0x70, 0x62, 0x5f, 0x62, 0x6a, 0x6c, 0xaa, 0x02, 0x06, 0x50, 0x62, 0x2e, 0x42, 0x6a, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bjl_proto_rawDescOnce sync.Once
	file_bjl_proto_rawDescData = file_bjl_proto_rawDesc
)

func file_bjl_proto_rawDescGZIP() []byte {
	file_bjl_proto_rawDescOnce.Do(func() {
		file_bjl_proto_rawDescData = protoimpl.X.CompressGZIP(file_bjl_proto_rawDescData)
	})
	return file_bjl_proto_rawDescData
}

var file_bjl_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_bjl_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bjl_proto_goTypes = []interface{}{
	(BjlLevel)(0),                 // 0: pb_bjl.BjlLevel
	(EnumBetArea)(0),              // 1: pb_bjl.EnumBetArea
	(EnumWinType)(0),              // 2: pb_bjl.EnumWinType
	(*ReqJoinRoom)(nil),           // 3: pb_bjl.ReqJoinRoom
	(*RespJoinRoom)(nil),          // 4: pb_bjl.RespJoinRoom
	(*ReqJoinDesk)(nil),           // 5: pb_bjl.ReqJoinDesk
	(*RespJoinDesk)(nil),          // 6: pb_bjl.RespJoinDesk
	(*BetInfo)(nil),               // 7: pb_bjl.BetInfo
	(*BroadcastStatusChange)(nil), // 8: pb_bjl.BroadcastStatusChange
	(*BroadcastPlayerBet)(nil),    // 9: pb_bjl.BroadcastPlayerBet
	(*NotifyBet)(nil),             // 10: pb_bjl.NotifyBet
	(*BroadcastPokerShow)(nil),    // 11: pb_bjl.BroadcastPokerShow
	(*Result)(nil),                // 12: pb_bjl.Result
	(*RespJoinRoom_DeskInfo)(nil), // 13: pb_bjl.RespJoinRoom.DeskInfo
}
var file_bjl_proto_depIdxs = []int32{
	13, // 0: pb_bjl.RespJoinRoom.info:type_name -> pb_bjl.RespJoinRoom.DeskInfo
	7,  // 1: pb_bjl.RespJoinDesk.BetInfos:type_name -> pb_bjl.BetInfo
	1,  // 2: pb_bjl.BetInfo.Area:type_name -> pb_bjl.EnumBetArea
	7,  // 3: pb_bjl.BroadcastPlayerBet.Info:type_name -> pb_bjl.BetInfo
	1,  // 4: pb_bjl.NotifyBet.Area:type_name -> pb_bjl.EnumBetArea
	2,  // 5: pb_bjl.Result.WinType:type_name -> pb_bjl.EnumWinType
	0,  // 6: pb_bjl.RespJoinRoom.DeskInfo.Level:type_name -> pb_bjl.BjlLevel
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_bjl_proto_init() }
func file_bjl_proto_init() {
	if File_bjl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bjl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqJoinDesk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinDesk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BetInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastPlayerBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NotifyBet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BroadcastPokerShow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bjl_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RespJoinRoom_DeskInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bjl_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bjl_proto_goTypes,
		DependencyIndexes: file_bjl_proto_depIdxs,
		EnumInfos:         file_bjl_proto_enumTypes,
		MessageInfos:      file_bjl_proto_msgTypes,
	}.Build()
	File_bjl_proto = out.File
	file_bjl_proto_rawDesc = nil
	file_bjl_proto_goTypes = nil
	file_bjl_proto_depIdxs = nil
}
